package llc.redstone.systemsdata.enums

import llc.redstone.systemsdata.KeyedLabeled

sealed class Sound(override val label: String, override val key: String) : KeyedLabeled {
    override fun toString(): String = key

    class Custom(val sound: String): Sound(sound, sound)
    data object AmbienceCave : Sound("Ambience Cave", "ambient.cave.cave")
    data object AmbienceRain : Sound("Ambience Rain", "ambient.weather.rain")
    data object AmbienceThunder : Sound("Ambience Thunder", "ambient.weather.thunder")
    data object AnvilBreak : Sound("Anvil Break", "random.anvil_break")
    data object AnvilLand : Sound("Anvil Land", "random.anvil_land")
    data object AnvilUse : Sound("Anvil Use", "random.anvil_use")
    data object ArrowHit : Sound("Arrow Hit", "random.bowhit")
    data object Burp : Sound("Burp", "random.burp")
    data object ChestClose : Sound("Chest Close", "random.chestclosed")
    data object ChestOpen : Sound("Chest Open", "random.chestopen")
    data object Click : Sound("Click", "random.click")
    data object DoorClose : Sound("Door Close", "random.door_close")
    data object DoorOpen : Sound("Door Open", "random.door_open")
    data object Drink : Sound("Drink", "random.drink")
    data object Eat : Sound("Eat", "random.eat")
    data object Explode : Sound("Explode", "random.explode")
    data object FallBig : Sound("Fall Big", "game.player.hurt.fall.big")
    data object FallSmall : Sound("Fall Small", "game.player.hurt.fall.small")
    data object Fizz : Sound("Fizz", "random.fizz")
    data object Fuse : Sound("Fuse", "game.tnt.primed")
    data object Glass : Sound("Glass", "dig.glass")
    data object HurtFlesh : Sound("Hurt Flesh", "game.player.hurt")
    data object ItemBreak : Sound("Item Break", "random.break")
    data object ItemPickup : Sound("Item Pickup", "random.pop")
    data object LavaPop : Sound("Lava Pop", "liquid.lavapop")
    data object LevelUp : Sound("Level Up", "random.levelup")
    data object NoteBass : Sound("Note Bass", "note.bass")
    data object NotePiano : Sound("Note Piano", "note.harp")
    data object NoteBassDrum : Sound("Note Bass Drum", "note.bd")
    data object NoteSticks : Sound("Note Sticks", "note.hat")
    data object NoteBassGuitar : Sound("Note Bass Guitar", "note.bassattack")
    data object NoteSnareDrum : Sound("Note Snare Drum", "note.snare")
    data object NotePling : Sound("Note Pling", "note.pling")
    data object OrbPickup : Sound("Orb Pickup", "random.orb")
    data object ShootArrow : Sound("Shoot Arrow", "random.bow")
    data object Splash : Sound("Splash", "game.player.swim.splash")
    data object Swim : Sound("Swim", "game.player.swim")
    data object WoodClick : Sound("Wood Click", "random.wood_click")
    data object BatDeath : Sound("Bat Death", "mob.bat.death")
    data object BatHurt : Sound("Bat Hurt", "mob.bat.hurt")
    data object BatIdle : Sound("Bat Idle", "mob.bat.idle")
    data object BatLoop : Sound("Bat Loop", "mob.bat.loop")
    data object BatTakeoff : Sound("Bat Takeoff", "mob.bat.takeoff")
    data object BlazeBreath : Sound("Blaze Breath", "mob.blaze.breathe")
    data object BlazeDeath : Sound("Blaze Death", "mob.blaze.death")
    data object BlazeHit : Sound("Blaze Hit", "mob.blaze.hit")
    data object CatHiss : Sound("Cat Hiss", "mob.cat.hiss")
    data object CatHit : Sound("Cat Hit", "mob.cat.hitt")
    data object CatMeow : Sound("Cat Meow", "mob.cat.meow")
    data object CatPurr : Sound("Cat Purr", "mob.cat.purr")
    data object CatPurreow : Sound("Cat Purreow", "mob.cat.purreow")
    data object ChickenIdle : Sound("Chicken Idle", "mob.chicken.say")
    data object ChickenHurt : Sound("Chicken Hurt", "mob.chicken.hurt")
    data object ChickenEggPop : Sound("Chicken Egg Pop", "mob.chicken.plop")
    data object ChickenWalk : Sound("Chicken Walk", "mob.chicken.step")
    data object CowIdle : Sound("Cow Idle", "mob.cow.say")
    data object CowHurt : Sound("Cow Hurt", "mob.cow.hurt")
    data object CowWalk : Sound("Cow Walk", "mob.cow.step")
    data object CreeperHiss : Sound("Creeper Hiss", "mob.creeper.say")
    data object CreeperDeath : Sound("Creeper Death", "mob.creeper.death")
    data object EnderdragonDeath : Sound("Enderdragon Death", "mob.enderdragon.end")
    data object EnderdragonGrowl : Sound("Enderdragon Growl", "mob.enderdragon.growl")
    data object EnderdragonHit : Sound("Enderdragon Hit", "mob.enderdragon.hit")
    data object EnderdragonWings : Sound("Enderdragon Wings", "mob.enderdragon.wings")
    data object EndermanDeath : Sound("Enderman Death", "mob.endermen.death")
    data object EndermanHit : Sound("Enderman Hit", "mob.endermen.hit")
    data object EndermanIdle : Sound("Enderman Idle", "mob.endermen.idle")
    data object EndermanTeleport : Sound("Enderman Teleport", "mob.endermen.portal")
    data object EndermanScream : Sound("Enderman Scream", "mob.endermen.scream")
    data object EndermanStare : Sound("Enderman Stare", "mob.endermen.stare")
    data object GhastScream : Sound("Ghast Scream", "mob.ghast.scream")
    data object GhastScream2 : Sound("Ghast Scream2", "mob.ghast.affectionate_scream")
    data object GhastCharge : Sound("Ghast Charge", "mob.ghast.charge")
    data object GhastDeath : Sound("Ghast Death", "mob.ghast.death")
    data object GhastFireball : Sound("Ghast Fireball", "mob.ghast.fireball")
    data object GhastMoan : Sound("Ghast Moan", "mob.ghast.moan")
    data object GuardianHit : Sound("Guardian Hit", "mob.guardian.hit")
    data object GuardianIdle : Sound("Guardian Idle", "mob.guardian.idle")
    data object GuardianDeath : Sound("Guardian Death", "mob.guardian.death")
    data object GuardianElderHit : Sound("Guardian Elder Hit", "mob.guardian.elder.hit")
    data object GuardianElderIdle : Sound("Guardian Elder Idle", "mob.guardian.elder.idle")
    data object GuardianElderDeath : Sound("Guardian Elder Death", "mob.guardian.elder.death")
    data object GuardianLandHit : Sound("Guardian Land Hit", "mob.guardian.land.hit")
    data object GuardianLandIdle : Sound("Guardian Land Idle", "mob.guardian.land.idle")
    data object GuardianLandDeath : Sound("Guardian Land Death", "mob.guardian.land.death")
    data object GuardianCurse : Sound("Guardian Curse", "mob.guardian.curse")
    data object GuardianAttack : Sound("Guardian Attack", "mob.guardian.attack")
    data object GuardianFlop : Sound("Guardian Flop", "mob.guardian.flop")
    data object IrongolemDeath : Sound("Irongolem Death", "mob.irongolem.death")
    data object IrongolemHit : Sound("Irongolem Hit", "mob.irongolem.hit")
    data object IrongolemThrow : Sound("Irongolem Throw", "mob.irongolem.throw")
    data object IrongolemWalk : Sound("Irongolem Walk", "mob.irongolem.walk")
    data object MagmacubeWalk : Sound("Magmacube Walk", "mob.magmacube.small")
    data object MagmacubeWalk2 : Sound("Magmacube Walk2", "mob.magmacube.big")
    data object MagmacubeJump : Sound("Magmacube Jump", "mob.magmacube.jump")
    data object PigIdle : Sound("Pig Idle", "mob.pig.say")
    data object PigDeath : Sound("Pig Death", "mob.pig.death")
    data object PigWalk : Sound("Pig Walk", "mob.pig.step")
    data object RabbitAmbient : Sound("Rabbit Ambient", "mob.rabbit.idle")
    data object RabbitDeath : Sound("Rabbit Death", "mob.rabbit.death")
    data object RabbitHurt : Sound("Rabbit Hurt", "mob.rabbit.hurt")
    data object RabbitJump : Sound("Rabbit Jump", "mob.rabbit.hop")
    data object SheepIdle : Sound("Sheep Idle", "mob.sheep.say")
    data object SheepShear : Sound("Sheep Shear", "mob.sheep.shear")
    data object SheepWalk : Sound("Sheep Walk", "mob.sheep.step")
    data object SilverfishHit : Sound("Silverfish Hit", "mob.silverfish.hit")
    data object SilverfishKill : Sound("Silverfish Kill", "mob.silverfish.kill")
    data object SilverfishIdle : Sound("Silverfish Idle", "mob.silverfish.say")
    data object SilverfishWalk : Sound("Silverfish Walk", "mob.silverfish.step")
    data object SkeletonIdle : Sound("Skeleton Idle", "mob.skeleton.say")
    data object SkeletonDeath : Sound("Skeleton Death", "mob.skeleton.death")
    data object SkeletonHurt : Sound("Skeleton Hurt", "mob.skeleton.hurt")
    data object SkeletonWalk : Sound("Skeleton Walk", "mob.skeleton.step")
    data object SlimeAttack : Sound("Slime Attack", "mob.slime.attack")
    data object SlimeWalk : Sound("Slime Walk", "mob.slime.small")
    data object SlimeWalk2 : Sound("Slime Walk2", "mob.slime.big")
    data object SpiderIdle : Sound("Spider Idle", "mob.spider.say")
    data object SpiderDeath : Sound("Spider Death", "mob.spider.death")
    data object SpiderWalk : Sound("Spider Walk", "mob.spider.step")
    data object WitherDeath : Sound("Wither Death", "mob.wither.death")
    data object WitherHurt : Sound("Wither Hurt", "mob.wither.hurt")
    data object WitherIdle : Sound("Wither Idle", "mob.wither.idle")
    data object WitherShoot : Sound("Wither Shoot", "mob.wither.shoot")
    data object WitherSpawn : Sound("Wither Spawn", "mob.wither.spawn")
    data object WolfBark : Sound("Wolf Bark", "mob.wolf.bark")
    data object WolfDeath : Sound("Wolf Death", "mob.wolf.death")
    data object WolfGrowl : Sound("Wolf Growl", "mob.wolf.growl")
    data object WolfHowl : Sound("Wolf Howl", "mob.wolf.howl")
    data object WolfHurt : Sound("Wolf Hurt", "mob.wolf.hurt")
    data object WolfPant : Sound("Wolf Pant", "mob.wolf.panting")
    data object WolfShake : Sound("Wolf Shake", "mob.wolf.shake")
    data object WolfWalk : Sound("Wolf Walk", "mob.wolf.step")
    data object WolfWhine : Sound("Wolf Whine", "mob.wolf.whine")
    data object ZombieMetal : Sound("Zombie Metal", "mob.zombie.metal")
    data object ZombieWood : Sound("Zombie Wood", "mob.zombie.wood")
    data object ZombieWoodbreak : Sound("Zombie Woodbreak", "mob.zombie.woodbreak")
    data object ZombieIdle : Sound("Zombie Idle", "mob.zombie.say")
    data object ZombieDeath : Sound("Zombie Death", "mob.zombie.death")
    data object ZombieHurt : Sound("Zombie Hurt", "mob.zombie.hurt")
    data object ZombieInfect : Sound("Zombie Infect", "mob.zombie.infect")
    data object ZombieUnfect : Sound("Zombie Unfect", "mob.zombie.unfect")
    data object ZombieRemedy : Sound("Zombie Remedy", "mob.zombie.remedy")
    data object ZombieWalk : Sound("Zombie Walk", "mob.zombie.step")
    data object ZombiePigIdle : Sound("Zombie Pig Idle", "mob.zombiepig.zpig")
    data object ZombiePigAngry : Sound("Zombie Pig Angry", "mob.zombiepig.zpigangry")
    data object ZombiePigDeath : Sound("Zombie Pig Death", "mob.zombiepig.zpigdeath")
    data object ZombiePigHurt : Sound("Zombie Pig Hurt", "mob.zombiepig.zpighurt")
    data object FireworkBlast : Sound("Firework Blast", "fireworks.blast")
    data object FireworkBlast2 : Sound("Firework Blast2", "fireworks.blast_far")
    data object FireworkLargeBlast : Sound("Firework Large Blast", "fireworks.largeBlast")
    data object FireworkLargeBlast2 : Sound("Firework Large Blast2", "fireworks.largeBlast_far")
    data object FireworkTwinkle : Sound("Firework Twinkle", "fireworks.twinkle")
    data object FireworkTwinkle2 : Sound("Firework Twinkle2", "fireworks.twinkle_far")
    data object FireworkLaunch : Sound("Firework Launch", "fireworks.launch")
    data object FireworksBlast : Sound("Fireworks Blast", "fireworks.blast")
    data object FireworksBlast2 : Sound("Fireworks Blast2", "fireworks.blast_far")
    data object FireworksLargeBlast : Sound("Fireworks Large Blast", "fireworks.largeBlast")
    data object FireworksLargeBlast2 : Sound("Fireworks Large Blast2", "fireworks.largeBlast_far")
    data object FireworksTwinkle : Sound("Fireworks Twinkle", "fireworks.twinkle")
    data object FireworksTwinkle2 : Sound("Fireworks Twinkle2", "fireworks.twinkle_far")
    data object FireworksLaunch : Sound("Fireworks Launch", "fireworks.launch")
    data object SuccessfulHit : Sound("Successful Hit", "random.successful_hit")
    data object HorseAngry : Sound("Horse Angry", "mob.horse.angry")
    data object HorseArmor : Sound("Horse Armor", "mob.horse.armor")
    data object HorseBreathe : Sound("Horse Breathe", "mob.horse.breathe")
    data object HorseDeath : Sound("Horse Death", "mob.horse.death")
    data object HorseGallop : Sound("Horse Gallop", "mob.horse.gallop")
    data object HorseHit : Sound("Horse Hit", "mob.horse.hit")
    data object HorseIdle : Sound("Horse Idle", "mob.horse.idle")
    data object HorseJump : Sound("Horse Jump", "mob.horse.jump")
    data object HorseLand : Sound("Horse Land", "mob.horse.land")
    data object HorseSaddle : Sound("Horse Saddle", "mob.horse.leather")
    data object HorseSoft : Sound("Horse Soft", "mob.horse.soft")
    data object HorseWood : Sound("Horse Wood", "mob.horse.wood")
    data object DonkeyAngry : Sound("Donkey Angry", "mob.horse.donkey.angry")
    data object DonkeyDeath : Sound("Donkey Death", "mob.horse.donkey.death")
    data object DonkeyHit : Sound("Donkey Hit", "mob.horse.donkey.hit")
    data object DonkeyIdle : Sound("Donkey Idle", "mob.horse.donkey.idle")
    data object HorseSkeletonDeath : Sound("Horse Skeleton Death", "mob.horse.skeleton.death")
    data object HorseSkeletonHit : Sound("Horse Skeleton Hit", "mob.horse.skeleton.hit")
    data object HorseSkeletonIdle : Sound("Horse Skeleton Idle", "mob.horse.skeleton.idle")
    data object HorseZombieDeath : Sound("Horse Zombie Death", "mob.horse.zombie.death")
    data object HorseZombieHit : Sound("Horse Zombie Hit", "mob.horse.zombie.hit")
    data object HorseZombieIdle : Sound("Horse Zombie Idle", "mob.horse.zombie.idle")
    data object VillagerDeath : Sound("Villager Death", "mob.villager.death")
    data object VillagerHaggle : Sound("Villager Haggle", "mob.villager.haggle")
    data object VillagerHit : Sound("Villager Hit", "mob.villager.hit")
    data object VillagerIdle : Sound("Villager Idle", "mob.villager.idle")
    data object VillagerNo : Sound("Villager No", "mob.villager.no")
    data object VillagerYes : Sound("Villager Yes", "mob.villager.yes")

    data object AmbientCave : Sound("Ambient Cave", "ambient.cave")
    data object BlockAnvilBreak : Sound("Block Anvil Break", "block.anvil.break")
    data object BlockAnvilDestroy : Sound("Block Anvil Destroy", "block.anvil.destroy")
    data object BlockAnvilFall : Sound("Block Anvil Fall", "block.anvil.fall")
    data object BlockAnvilHit : Sound("Block Anvil Hit", "block.anvil.hit")
    data object BlockAnvilLand : Sound("Block Anvil Land", "block.anvil.land")
    data object BlockAnvilPlace : Sound("Block Anvil Place", "block.anvil.place")
    data object BlockAnvilStep : Sound("Block Anvil Step", "block.anvil.step")
    data object BlockAnvilUse : Sound("Block Anvil Use", "block.anvil.use")
    data object BlockChestClose : Sound("Block Chest Close", "block.chest.close")
    data object BlockChestLocked : Sound("Block Chest Locked", "block.chest.locked")
    data object BlockChestOpen : Sound("Block Chest Open", "block.chest.open")
    data object BlockCobwebBreak : Sound("Block Cobweb Break", "block.cobweb.break")
    data object BlockCobwebFall : Sound("Block Cobweb Fall", "block.cobweb.fall")
    data object BlockCobwebHit : Sound("Block Cobweb Hit", "block.cobweb.hit")
    data object BlockCobwebPlace : Sound("Block Cobweb Place", "block.cobweb.place")
    data object BlockCobwebStep : Sound("Block Cobweb Step", "block.cobweb.step")
    data object BlockComparatorClick : Sound("Block Comparator Click", "block.comparator.click")
    data object BlockCropBreak : Sound("Block Crop Break", "block.crop.break")
    data object BlockDispenserDispense : Sound("Block Dispenser Dispense", "block.dispenser.dispense")
    data object BlockDispenserFail : Sound("Block Dispenser Fail", "block.dispenser.fail")
    data object BlockDispenserLaunch : Sound("Block Dispenser Launch", "block.dispenser.launch")
    data object BlockFenceGateClose : Sound("Block Fence Gate Close", "block.fence_gate.close")
    data object BlockFenceGateOpen : Sound("Block Fence Gate Open", "block.fence_gate.open")
    data object BlockFireAmbient : Sound("Block Fire Ambient", "block.fire.ambient")
    data object BlockFireExtinguish : Sound("Block Fire Extinguish", "block.fire.extinguish")
    data object BlockFurnaceFireCrackle : Sound("Block Furnace Fire Crackle", "block.furnace.fire_crackle")
    data object BlockGlassBreak : Sound("Block Glass Break", "block.glass.break")
    data object BlockGlassFall : Sound("Block Glass Fall", "block.glass.fall")
    data object BlockGlassHit : Sound("Block Glass Hit", "block.glass.hit")
    data object BlockGlassPlace : Sound("Block Glass Place", "block.glass.place")
    data object BlockGlassStep : Sound("Block Glass Step", "block.glass.step")
    data object BlockGrassBreak : Sound("Block Grass Break", "block.grass.break")
    data object BlockGrassFall : Sound("Block Grass Fall", "block.grass.fall")
    data object BlockGrassHit : Sound("Block Grass Hit", "block.grass.hit")
    data object BlockGrassPlace : Sound("Block Grass Place", "block.grass.place")
    data object BlockGrassStep : Sound("Block Grass Step", "block.grass.step")
    data object BlockGravelBreak : Sound("Block Gravel Break", "block.gravel.break")
    data object BlockGravelFall : Sound("Block Gravel Fall", "block.gravel.fall")
    data object BlockGravelHit : Sound("Block Gravel Hit", "block.gravel.hit")
    data object BlockGravelPlace : Sound("Block Gravel Place", "block.gravel.place")
    data object BlockGravelStep : Sound("Block Gravel Step", "block.gravel.step")
    data object BlockGrowingPlantCrop : Sound("Block Growing Plant Crop", "block.growing_plant.crop")
    data object BlockIronDoorClose : Sound("Block Iron Door Close", "block.iron_door.close")
    data object BlockIronDoorOpen : Sound("Block Iron Door Open", "block.iron_door.open")
    data object BlockIronTrapdoorClose : Sound("Block Iron Trapdoor Close", "block.iron_trapdoor.close")
    data object BlockIronTrapdoorOpen : Sound("Block Iron Trapdoor Open", "block.iron_trapdoor.open")
    data object BlockLadderBreak : Sound("Block Ladder Break", "block.ladder.break")
    data object BlockLadderFall : Sound("Block Ladder Fall", "block.ladder.fall")
    data object BlockLadderHit : Sound("Block Ladder Hit", "block.ladder.hit")
    data object BlockLadderPlace : Sound("Block Ladder Place", "block.ladder.place")
    data object BlockLadderStep : Sound("Block Ladder Step", "block.ladder.step")
    data object BlockLavaAmbient : Sound("Block Lava Ambient", "block.lava.ambient")
    data object BlockLavaExtinguish : Sound("Block Lava Extinguish", "block.lava.extinguish")
    data object BlockLavaPop : Sound("Block Lava Pop", "block.lava.pop")
    data object BlockLeverClick : Sound("Block Lever Click", "block.lever.click")
    data object BlockLilyPadPlace : Sound("Block Lily Pad Place", "block.lily_pad.place")
    data object BlockMetalBreak : Sound("Block Metal Break", "block.metal.break")
    data object BlockMetalFall : Sound("Block Metal Fall", "block.metal.fall")
    data object BlockMetalHit : Sound("Block Metal Hit", "block.metal.hit")
    data object BlockMetalPlace : Sound("Block Metal Place", "block.metal.place")
    data object BlockMetalPressurePlateClickOff : Sound("Block Metal Pressure Plate Click Off", "block.metal_pressure_plate.click_off")
    data object BlockMetalPressurePlateClickOn : Sound("Block Metal Pressure Plate Click On", "block.metal_pressure_plate.click_on")
    data object BlockMetalStep : Sound("Block Metal Step", "block.metal.step")
    data object BlockMossBreak : Sound("Block Moss Break", "block.moss.break")
    data object BlockNetherBricksBreak : Sound("Block Nether Bricks Break", "block.nether_bricks.break")
    data object BlockNetherBricksFall : Sound("Block Nether Bricks Fall", "block.nether_bricks.fall")
    data object BlockNetherBricksHit : Sound("Block Nether Bricks Hit", "block.nether_bricks.hit")
    data object BlockNetherBricksPlace : Sound("Block Nether Bricks Place", "block.nether_bricks.place")
    data object BlockNetherBricksStep : Sound("Block Nether Bricks Step", "block.nether_bricks.step")
    data object BlockNetherOreBreak : Sound("Block Nether Ore Break", "block.nether_ore.break")
    data object BlockNetherOreFall : Sound("Block Nether Ore Fall", "block.nether_ore.fall")
    data object BlockNetherOreHit : Sound("Block Nether Ore Hit", "block.nether_ore.hit")
    data object BlockNetherOrePlace : Sound("Block Nether Ore Place", "block.nether_ore.place")
    data object BlockNetherOreStep : Sound("Block Nether Ore Step", "block.nether_ore.step")
    data object BlockNetherWartBreak : Sound("Block Nether Wart Break", "block.nether_wart.break")
    data object BlockNetherWoodBreak : Sound("Block Nether Wood Break", "block.nether_wood.break")
    data object BlockNetherrackBreak : Sound("Block Netherrack Break", "block.netherrack.break")
    data object BlockNetherrackFall : Sound("Block Netherrack Fall", "block.netherrack.fall")
    data object BlockNetherrackHit : Sound("Block Netherrack Hit", "block.netherrack.hit")
    data object BlockNetherrackPlace : Sound("Block Netherrack Place", "block.netherrack.place")
    data object BlockNetherrackStep : Sound("Block Netherrack Step", "block.netherrack.step")
    data object BlockNoteBlockBasedrum : Sound("Block Note Block Basedrum", "block.note_block.basedrum")
    data object BlockNoteBlockBass : Sound("Block Note Block Bass", "block.note_block.bass")
    data object BlockNoteBlockBell : Sound("Block Note Block Bell", "block.note_block.bell")
    data object BlockNoteBlockChime : Sound("Block Note Block Chime", "block.note_block.chime")
    data object BlockNoteBlockFlute : Sound("Block Note Block Flute", "block.note_block.flute")
    data object BlockNoteBlockGuitar : Sound("Block Note Block Guitar", "block.note_block.guitar")
    data object BlockNoteBlockHarp : Sound("Block Note Block Harp", "block.note_block.harp")
    data object BlockNoteBlockHat : Sound("Block Note Block Hat", "block.note_block.hat")
    data object BlockNoteBlockPling : Sound("Block Note Block Pling", "block.note_block.pling")
    data object BlockNoteBlockSnare : Sound("Block Note Block Snare", "block.note_block.snare")
    data object BlockNoteBlockXylophone : Sound("Block Note Block Xylophone", "block.note_block.xylophone")
    data object BlockPistonContract : Sound("Block Piston Contract", "block.piston.contract")
    data object BlockPistonExtend : Sound("Block Piston Extend", "block.piston.extend")
    data object BlockPortalAmbient : Sound("Block Portal Ambient", "block.portal.ambient")
    data object BlockPortalTravel : Sound("Block Portal Travel", "block.portal.travel")
    data object BlockPortalTrigger : Sound("Block Portal Trigger", "block.portal.trigger")
    data object BlockRedstoneTorchBurnout : Sound("Block Redstone Torch Burnout", "block.redstone_torch.burnout")
    data object BlockSandBreak : Sound("Block Sand Break", "block.sand.break")
    data object BlockSandFall : Sound("Block Sand Fall", "block.sand.fall")
    data object BlockSandHit : Sound("Block Sand Hit", "block.sand.hit")
    data object BlockSandPlace : Sound("Block Sand Place", "block.sand.place")
    data object BlockSandStep : Sound("Block Sand Step", "block.sand.step")
    data object BlockSnowBreak : Sound("Block Snow Break", "block.snow.break")
    data object BlockSnowFall : Sound("Block Snow Fall", "block.snow.fall")
    data object BlockSnowHit : Sound("Block Snow Hit", "block.snow.hit")
    data object BlockSnowPlace : Sound("Block Snow Place", "block.snow.place")
    data object BlockSnowStep : Sound("Block Snow Step", "block.snow.step")
    data object BlockSoulSandBreak : Sound("Block Soul Sand Break", "block.soul_sand.break")
    data object BlockSoulSandFall : Sound("Block Soul Sand Fall", "block.soul_sand.fall")
    data object BlockSoulSandHit : Sound("Block Soul Sand Hit", "block.soul_sand.hit")
    data object BlockSoulSandPlace : Sound("Block Soul Sand Place", "block.soul_sand.place")
    data object BlockSoulSandStep : Sound("Block Soul Sand Step", "block.soul_sand.step")
    data object BlockSpawnerBreak : Sound("Block Spawner Break", "block.spawner.break")
    data object BlockSpawnerFall : Sound("Block Spawner Fall", "block.spawner.fall")
    data object BlockSpawnerHit : Sound("Block Spawner Hit", "block.spawner.hit")
    data object BlockSpawnerPlace : Sound("Block Spawner Place", "block.spawner.place")
    data object BlockSpawnerStep : Sound("Block Spawner Step", "block.spawner.step")
    data object BlockSpongeAbsorb : Sound("Block Sponge Absorb", "block.sponge.absorb")
    data object BlockSpongeBreak : Sound("Block Sponge Break", "block.sponge.break")
    data object BlockSpongeFall : Sound("Block Sponge Fall", "block.sponge.fall")
    data object BlockSpongeHit : Sound("Block Sponge Hit", "block.sponge.hit")
    data object BlockSpongePlace : Sound("Block Sponge Place", "block.sponge.place")
    data object BlockSpongeStep : Sound("Block Sponge Step", "block.sponge.step")
    data object BlockStemBreak : Sound("Block Stem Break", "block.stem.break")
    data object BlockStemFall : Sound("Block Stem Fall", "block.stem.fall")
    data object BlockStemHit : Sound("Block Stem Hit", "block.stem.hit")
    data object BlockStemPlace : Sound("Block Stem Place", "block.stem.place")
    data object BlockStemStep : Sound("Block Stem Step", "block.stem.step")
    data object BlockStoneBreak : Sound("Block Stone Break", "block.stone.break")
    data object BlockStoneButtonClickOff : Sound("Block Stone Button Click Off", "block.stone_button.click_off")
    data object BlockStoneButtonClickOn : Sound("Block Stone Button Click On", "block.stone_button.click_on")
    data object BlockStoneFall : Sound("Block Stone Fall", "block.stone.fall")
    data object BlockStoneHit : Sound("Block Stone Hit", "block.stone.hit")
    data object BlockStonePlace : Sound("Block Stone Place", "block.stone.place")
    data object BlockStonePressurePlateClickOff : Sound("Block Stone Pressure Plate Click Off", "block.stone_pressure_plate.click_off")
    data object BlockStonePressurePlateClickOn : Sound("Block Stone Pressure Plate Click On", "block.stone_pressure_plate.click_on")
    data object BlockStoneStep : Sound("Block Stone Step", "block.stone.step")
    data object BlockTripwireAttach : Sound("Block Tripwire Attach", "block.tripwire.attach")
    data object BlockTripwireClickOff : Sound("Block Tripwire Click Off", "block.tripwire_click_off")
    data object BlockTripwireClickOn : Sound("Block Tripwire Click On", "block.tripwire_click_on")
    data object BlockTripwireDetach : Sound("Block Tripwire Detach", "block.tripwire.detach")
    data object BlockVineBreak : Sound("Block Vine Break", "block.vine.break")
    data object BlockVineFall : Sound("Block Vine Fall", "block.vine.fall")
    data object BlockVineHit : Sound("Block Vine Hit", "block.vine.hit")
    data object BlockVinePlace : Sound("Block Vine Place", "block.vine.place")
    data object BlockVineStep : Sound("Block Vine Step", "block.vine.step")
    data object BlockWartBlockBreak : Sound("Block Wart Block Break", "block.wart_block.break")
    data object BlockWartBlockFall : Sound("Block Wart Block Fall", "block.wart_block.fall")
    data object BlockWartBlockHit : Sound("Block Wart Block Hit", "block.wart_block.hit")
    data object BlockWartBlockPlace : Sound("Block Wart Block Place", "block.wart_block.place")
    data object BlockWartBlockStep : Sound("Block Wart Block Step", "block.wart_block.step")
    data object BlockWaterAmbient : Sound("Block Water Ambient", "block.water.ambient")
    data object BlockWetSpongeBreak : Sound("Block Wet Sponge Break", "block.wet_sponge.break")
    data object BlockWetSpongeFall : Sound("Block Wet Sponge Fall", "block.wet_sponge.fall")
    data object BlockWetSpongeHit : Sound("Block Wet Sponge Hit", "block.wet_sponge.hit")
    data object BlockWetSpongePlace : Sound("Block Wet Sponge Place", "block.wet_sponge.place")
    data object BlockWetSpongeStep : Sound("Block Wet Sponge Step", "block.wet_sponge.step")
    data object BlockWoodBreak : Sound("Block Wood Break", "block.wood.break")
    data object BlockWoodFall : Sound("Block Wood Fall", "block.wood.fall")
    data object BlockWoodHit : Sound("Block Wood Hit", "block.wood.hit")
    data object BlockWoodPlace : Sound("Block Wood Place", "block.wood.place")
    data object BlockWoodStep : Sound("Block Wood Step", "block.wood.step")
    data object BlockWoodenButtonClickOff : Sound("Block Wooden Button Click Off", "block.wooden_button.click_off")
    data object BlockWoodenButtonClickOn : Sound("Block Wooden Button Click On", "block.wooden_button.click_on")
    data object BlockWoodenDoorClose : Sound("Block Wooden Door Close", "block.wooden_door.close")
    data object BlockWoodenDoorOpen : Sound("Block Wooden Door Open", "block.wooden_door.open")
    data object BlockWoodenPressurePlateClickOff : Sound("Block Wooden Pressure Plate Click Off", "block.wooden_pressure_plate.click_off")
    data object BlockWoodenPressurePlateClickOn : Sound("Block Wooden Pressure Plate Click On", "block.wooden_pressure_plate.click_on")
    data object BlockWoodenTrapdoorClose : Sound("Block Wooden Trapdoor Close", "block.wooden_trapdoor.close")
    data object BlockWoodenTrapdoorOpen : Sound("Block Wooden Trapdoor Open", "block.wooden_trapdoor.open")
    data object BlockWoolBreak : Sound("Block Wool Break", "block.wool.break")
    data object BlockWoolFall : Sound("Block Wool Fall", "block.wool.fall")
    data object BlockWoolHit : Sound("Block Wool Hit", "block.wool.hit")
    data object BlockWoolPlace : Sound("Block Wool Place", "block.wool.place")
    data object BlockWoolStep : Sound("Block Wool Step", "block.wool.step")
    data object EntityArmorStandBreak : Sound("Entity Armor Stand Break", "entity.armor_stand.break")
    data object EntityArmorStandFall : Sound("Entity Armor Stand Fall", "entity.armor_stand.fall")
    data object EntityArmorStandHit : Sound("Entity Armor Stand Hit", "entity.armor_stand.hit")
    data object EntityArmorStandPlace : Sound("Entity Armor Stand Place", "entity.armor_stand.place")
    data object EntityArrowHit : Sound("Entity Arrow Hit", "entity.arrow_hit")
    data object EntityArrowHitPlayer : Sound("Entity Arrow Hit Player", "entity.arrow_hit.player")
    data object EntityArrowShoot : Sound("Entity Arrow Shoot", "entity.arrow.shoot")
    data object EntityBatAmbient : Sound("Entity Bat Ambient", "entity.bat.ambient")
    data object EntityBatDeath : Sound("Entity Bat Death", "entity.bat.death")
    data object EntityBatHurt : Sound("Entity Bat Hurt", "entity.bat.hurt")
    data object EntityBatLoop : Sound("Entity Bat Loop", "entity.bat.loop")
    data object EntityBatTakeoff : Sound("Entity Bat Takeoff", "entity.bat.takeoff")
    data object EntityBlazeAmbient : Sound("Entity Blaze Ambient", "entity.blaze.ambient")
    data object EntityBlazeBurn : Sound("Entity Blaze Burn", "entity.blaze.burn")
    data object EntityBlazeDeath : Sound("Entity Blaze Death", "entity.blaze.death")
    data object EntityBlazeHurt : Sound("Entity Blaze Hurt", "entity.blaze.hurt")
    data object EntityBlazeShoot : Sound("Entity Blaze Shoot", "entity.blaze.shoot")
    data object EntityCatAmbient : Sound("Entity Cat Ambient", "entity.cat.ambient")
    data object EntityCatDeath : Sound("Entity Cat Death", "entity.cat.death")
    data object EntityCatHiss : Sound("Entity Cat Hiss", "entity.cat.hiss")
    data object EntityCatHurt : Sound("Entity Cat Hurt", "entity.cat.hurt")
    data object EntityCatPurr : Sound("Entity Cat Purr", "entity.cat.purr")
    data object EntityChickenAmbient : Sound("Entity Chicken Ambient", "entity.chicken.ambient")
    data object EntityChickenDeath : Sound("Entity Chicken Death", "entity.chicken.death")
    data object EntityChickenEgg : Sound("Entity Chicken Egg", "entity.chicken.egg")
    data object EntityChickenHurt : Sound("Entity Chicken Hurt", "entity.chicken.hurt")
    data object EntityChickenStep : Sound("Entity Chicken Step", "entity.chicken.step")
    data object EntityCowAmbient : Sound("Entity Cow Ambient", "entity.cow.ambient")
    data object EntityCowDeath : Sound("Entity Cow Death", "entity.cow.death")
    data object EntityCowHurt : Sound("Entity Cow Hurt", "entity.cow.hurt")
    data object EntityCowMilk : Sound("Entity Cow Milk", "entity.cow.milk")
    data object EntityCowStep : Sound("Entity Cow Step", "entity.cow.step")
    data object EntityCreeperDeath : Sound("Entity Creeper Death", "entity.creeper.death")
    data object EntityCreeperHurt : Sound("Entity Creeper Hurt", "entity.creeper.hurt")
    data object EntityCreeperPrimed : Sound("Entity Creeper Primed", "entity.creeper.primed")
    data object EntityDonkeyAmbient : Sound("Entity Donkey Ambient", "entity.donkey.ambient")
    data object EntityDonkeyAngry : Sound("Entity Donkey Angry", "entity.donkey.angry")
    data object EntityDonkeyChest : Sound("Entity Donkey Chest", "entity.donkey.chest")
    data object EntityDonkeyDeath : Sound("Entity Donkey Death", "entity.donkey.death")
    data object EntityDonkeyEat : Sound("Entity Donkey Eat", "entity.donkey.eat")
    data object EntityDonkeyHurt : Sound("Entity Donkey Hurt", "entity.donkey.hurt")
    data object EntityDonkeyJump : Sound("Entity Donkey Jump", "entity.donkey.jump")
    data object EntityEggThrow : Sound("Entity Egg Throw", "entity.egg.throw")
    data object EntityElderGuardianAmbient : Sound("Entity Elder Guardian Ambient", "entity.elder_guardian.ambient")
    data object EntityElderGuardianAmbientLand : Sound("Entity Elder Guardian Ambient Land", "entity.elder_guardian.ambient_land")
    data object EntityElderGuardianCurse : Sound("Entity Elder Guardian Curse", "entity.elder_guardian.curse")
    data object EntityElderGuardianDeath : Sound("Entity Elder Guardian Death", "entity.elder_guardian.death")
    data object EntityElderGuardianDeathLand : Sound("Entity Elder Guardian Death Land", "entity.elder_guardian.death_land")
    data object EntityElderGuardianFlop : Sound("Entity Elder Guardian Flop", "entity.elder_guardian.flop")
    data object EntityElderGuardianHurt : Sound("Entity Elder Guardian Hurt", "entity.elder_guardian.hurt")
    data object EntityElderGuardianHurtLand : Sound("Entity Elder Guardian Hurt Land", "entity.elder_guardian.hurt_land")
    data object EntityEnderDragonAmbient : Sound("Entity Ender Dragon Ambient", "entity.ender_dragon.ambient")
    data object EntityEnderDragonDeath : Sound("Entity Ender Dragon Death", "entity.ender_dragon.death")
    data object EntityEnderDragonFlap : Sound("Entity Ender Dragon Flap", "entity.ender_dragon.flap")
    data object EntityEnderDragonGrowl : Sound("Entity Ender Dragon Growl", "entity.ender_dragon.growl")
    data object EntityEnderDragonHurt : Sound("Entity Ender Dragon Hurt", "entity.ender_dragon.hurt")
    data object EntityEnderDragonShoot : Sound("Entity Ender Dragon Shoot", "entity.ender_dragon.shoot")
    data object EntityEnderEyeDeath : Sound("Entity Ender Eye Death", "entity.ender_eye.death")
    data object EntityEnderEyeLaunch : Sound("Entity Ender Eye Launch", "entity.ender_eye.launch")
    data object EntityEnderPearlThrow : Sound("Entity Ender Pearl Throw", "entity.ender_pearl.throw")
    data object EntityEndermanAmbient : Sound("Entity Enderman Ambient", "entity.enderman.ambient")
    data object EntityEndermanDeath : Sound("Entity Enderman Death", "entity.enderman.death")
    data object EntityEndermanHurt : Sound("Entity Enderman Hurt", "entity.enderman.hurt")
    data object EntityEndermanScream : Sound("Entity Enderman Scream", "entity.enderman.scream")
    data object EntityEndermanStare : Sound("Entity Enderman Stare", "entity.enderman.stare")
    data object EntityEndermanTeleport : Sound("Entity Enderman Teleport", "entity.enderman.teleport")
    data object EntityEndermiteAmbient : Sound("Entity Endermite Ambient", "entity.endermite.ambient")
    data object EntityEndermiteDeath : Sound("Entity Endermite Death", "entity.endermite.death")
    data object EntityEndermiteHurt : Sound("Entity Endermite Hurt", "entity.endermite.hurt")
    data object EntityEndermiteStep : Sound("Entity Endermite Step", "entity.endermite.step")
    data object EntityExperienceBottleThrow : Sound("Entity Experience Bottle Throw", "entity.experience_bottle.throw")
    data object EntityExperienceOrbPickup : Sound("Entity Experience Orb Pickup", "entity.experience_orb.pickup")
    data object EntityFireworkRocketBlast : Sound("Entity Firework Rocket Blast", "entity.firework_rocket.blast")
    data object EntityFireworkRocketBlastFar : Sound("Entity Firework Rocket Blast Far", "entity.firework_rocket.blast_far")
    data object EntityFireworkRocketLargeBlast : Sound("Entity Firework Rocket Large Blast", "entity.firework_rocket.large_blast")
    data object EntityFireworkRocketLargeBlastFar : Sound("Entity Firework Rocket Large Blast Far", "entity.firework_rocket.large_blast_far")
    data object EntityFireworkRocketLaunch : Sound("Entity Firework Rocket Launch", "entity.firework_rocket.launch")
    data object EntityFireworkRocketShoot : Sound("Entity Firework Rocket Shoot", "entity.firework_rocket.shoot")
    data object EntityFireworkRocketTwinkle : Sound("Entity Firework Rocket Twinkle", "entity.firework_rocket.twinkle")
    data object EntityFireworkRocketTwinkleFar : Sound("Entity Firework Rocket Twinkle Far", "entity.firework_rocket.twinkle_far")
    data object EntityFishingBobberSplash : Sound("Entity Fishing Bobber Splash", "entity.fishing_bobber.splash")
    data object EntityFishingBobberThrow : Sound("Entity Fishing Bobber Throw", "entity.fishing_bobber.throw")
    data object EntityGenericBigFall : Sound("Entity Generic Big Fall", "entity.generic.big_fall")
    data object EntityGenericBurn : Sound("Entity Generic Burn", "entity.generic.burn")
    data object EntityGenericDeath : Sound("Entity Generic Death", "entity.generic.death")
    data object EntityGenericDrink : Sound("Entity Generic Drink", "entity.generic.drink")
    data object EntityGenericEat : Sound("Entity Generic Eat", "entity.generic.eat")
    data object EntityGenericExplode : Sound("Entity Generic Explode", "entity.generic.explode")
    data object EntityGenericExtinguishFire : Sound("Entity Generic Extinguish Fire", "entity.generic.extinguish_fire")
    data object EntityGenericHurt : Sound("Entity Generic Hurt", "entity.generic.hurt")
    data object EntityGenericSmallFall : Sound("Entity Generic Small Fall", "entity.generic.small_fall")
    data object EntityGenericSplash : Sound("Entity Generic Splash", "entity.generic.splash")
    data object EntityGenericSwim : Sound("Entity Generic Swim", "entity.generic.swim")
    data object EntityGhastAmbient : Sound("Entity Ghast Ambient", "entity.ghast.ambient")
    data object EntityGhastDeath : Sound("Entity Ghast Death", "entity.ghast.death")
    data object EntityGhastHurt : Sound("Entity Ghast Hurt", "entity.ghast.hurt")
    data object EntityGhastScream : Sound("Entity Ghast Scream", "entity.ghast.scream")
    data object EntityGhastShoot : Sound("Entity Ghast Shoot", "entity.ghast.shoot")
    data object EntityGhastWarn : Sound("Entity Ghast Warn", "entity.ghast.warn")
    data object EntityGuardianAmbient : Sound("Entity Guardian Ambient", "entity.guardian.ambient")
    data object EntityGuardianAmbientLand : Sound("Entity Guardian Ambient Land", "entity.guardian.ambient_land")
    data object EntityGuardianAttack : Sound("Entity Guardian Attack", "entity.guardian.attack")
    data object EntityGuardianDeath : Sound("Entity Guardian Death", "entity.guardian.death")
    data object EntityGuardianDeathLand : Sound("Entity Guardian Death Land", "entity.guardian.death_land")
    data object EntityGuardianFlop : Sound("Entity Guardian Flop", "entity.guardian.flop")
    data object EntityGuardianHurt : Sound("Entity Guardian Hurt", "entity.guardian.hurt")
    data object EntityGuardianHurtLand : Sound("Entity Guardian Hurt Land", "entity.guardian.hurt_land")
    data object EntityHorseAmbient : Sound("Entity Horse Ambient", "entity.horse_ambient")
    data object EntityHorseAngry : Sound("Entity Horse Angry", "entity.horse.angry")
    data object EntityHorseArmor : Sound("Entity Horse Armor", "entity.horse.armor")
    data object EntityHorseBreathe : Sound("Entity Horse Breathe", "entity.horse.breathe")
    data object EntityHorseDeath : Sound("Entity Horse Death", "entity.horse_death")
    data object EntityHorseEat : Sound("Entity Horse Eat", "entity.horse.eat")
    data object EntityHorseGallop : Sound("Entity Horse Gallop", "entity.horse.gallop")
    data object EntityHorseHurt : Sound("Entity Horse Hurt", "entity.horse_hurt")
    data object EntityHorseJump : Sound("Entity Horse Jump", "entity.horse.jump")
    data object EntityHorseLand : Sound("Entity Horse Land", "entity.horse.land")
    data object EntityHorseSaddle : Sound("Entity Horse Saddle", "entity.horse.saddle")
    data object EntityHorseStep : Sound("Entity Horse Step", "entity.horse.step")
    data object EntityHorseStepWood : Sound("Entity Horse Step Wood", "entity.horse.step_wood")
    data object EntityHostileBigFall : Sound("Entity Hostile Big Fall", "entity.hostile.big_fall")
    data object EntityHostileDeath : Sound("Entity Hostile Death", "entity.hostile.death")
    data object EntityHostileHurt : Sound("Entity Hostile Hurt", "entity.hostile.hurt")
    data object EntityHostileSmallFall : Sound("Entity Hostile Small Fall", "entity.hostile.small_fall")
    data object EntityHostileSplash : Sound("Entity Hostile Splash", "entity.hostile.splash")
    data object EntityHostileSwim : Sound("Entity Hostile Swim", "entity.hostile.swim")
    data object EntityIronGolemAttack : Sound("Entity Iron Golem Attack", "entity.iron_golem.attack")
    data object EntityIronGolemDamage : Sound("Entity Iron Golem Damage", "entity.iron_golem.damage")
    data object EntityIronGolemDeath : Sound("Entity Iron Golem Death", "entity.iron_golem.death")
    data object EntityIronGolemHurt : Sound("Entity Iron Golem Hurt", "entity.iron_golem.hurt")
    data object EntityIronGolemRepair : Sound("Entity Iron Golem Repair", "entity.iron_golem.repair")
    data object EntityIronGolemStep : Sound("Entity Iron Golem Step", "entity.iron_golem.step")
    data object EntityItemBreak : Sound("Entity Item Break", "entity.item.break")
    data object EntityItemPickup : Sound("Entity Item Pickup", "entity.item.pickup")
    data object EntityLightningBoltImpact : Sound("Entity Lightning Bolt Impact", "entity.lightning_bolt.impact")
    data object EntityLightningBoltThunder : Sound("Entity Lightning Bolt Thunder", "entity.lightning_bolt.thunder")
    data object EntityLingeringPotionThrow : Sound("Entity Lingering Potion Throw", "entity.lingering.potion.throw")
    data object EntityMagmaCubeDeath : Sound("Entity Magma Cube Death", "entity.magma_cube.death")
    data object EntityMagmaCubeDeathSmall : Sound("Entity Magma Cube Death Small", "entity.magma_cube.death_small")
    data object EntityMagmaCubeHurt : Sound("Entity Magma Cube Hurt", "entity.magma_cube.hurt")
    data object EntityMagmaCubeHurtSmall : Sound("Entity Magma Cube Hurt Small", "entity.magma_cube.hurt_small")
    data object EntityMagmaCubeJump : Sound("Entity Magma Cube Jump", "entity.magma_cube.jump")
    data object EntityMagmaCubeSquish : Sound("Entity Magma Cube Squish", "entity.magma_cube.squish")
    data object EntityMagmaCubeSquishSmall : Sound("Entity Magma Cube Squish Small", "entity.magma_cube.squish_small")
    data object EntityMinecartInside : Sound("Entity Minecart Inside", "entity.minecart.inside")
    data object EntityMinecartInsideUnderwater : Sound("Entity Minecart Inside Underwater", "entity.minecart.inside.underwater")
    data object EntityMinecartRiding : Sound("Entity Minecart Riding", "entity.minecart.riding")
    data object EntityMooshroomConvert : Sound("Entity Mooshroom Convert", "entity.mooshroom.convert")
    data object EntityMooshroomEat : Sound("Entity Mooshroom Eat", "entity.mooshroom.eat")
    data object EntityMooshroomMilk : Sound("Entity Mooshroom Milk", "entity.mooshroom.milk")
    data object EntityMooshroomShear : Sound("Entity Mooshroom Shear", "entity.mooshroom.shear")
    data object EntityMooshroomSuspiciousMilk : Sound("Entity Mooshroom Suspicious Milk", "entity.mooshroom.suspicious_milk")
    data object EntityMuleAmbient : Sound("Entity Mule Ambient", "entity.mule.ambient")
    data object EntityMuleAngry : Sound("Entity Mule Angry", "entity.mule.angry")
    data object EntityMuleChest : Sound("Entity Mule Chest", "entity.mule.chest")
    data object EntityMuleDeath : Sound("Entity Mule Death", "entity.mule.death")
    data object EntityMuleEat : Sound("Entity Mule Eat", "entity.mule.eat")
    data object EntityMuleHurt : Sound("Entity Mule Hurt", "entity.mule.hurt")
    data object EntityMuleJump : Sound("Entity Mule Jump", "entity.mule.jump")
    data object EntityOcelotAmbient : Sound("Entity Ocelot Ambient", "entity.ocelot.ambient")
    data object EntityOcelotDeath : Sound("Entity Ocelot Death", "entity.ocelot.death")
    data object EntityOcelotHurt : Sound("Entity Ocelot Hurt", "entity.ocelot.hurt")
    data object EntityPigAmbient : Sound("Entity Pig Ambient", "entity.pig.ambient")
    data object EntityPigDeath : Sound("Entity Pig Death", "entity.pig.death")
    data object EntityPigHurt : Sound("Entity Pig Hurt", "entity.pig.hurt")
    data object EntityPigSaddle : Sound("Entity Pig Saddle", "entity.pig.saddle")
    data object EntityPigStep : Sound("Entity Pig Step", "entity.pig.step")
    data object EntityPlayerBigFall : Sound("Entity Player Big Fall", "entity.player.big_fall")
    data object EntityPlayerBreath : Sound("Entity Player Breath", "entity.player.breath")
    data object EntityPlayerBurp : Sound("Entity Player Burp", "entity.player.burp")
    data object EntityPlayerDeath : Sound("Entity Player Death", "entity.player.death")
    data object EntityPlayerHurt : Sound("Entity Player Hurt", "entity.player.hurt")
    data object EntityPlayerHurtDrown : Sound("Entity Player Hurt Drown", "entity.player.hurt_drown")
    data object EntityPlayerHurtFreeze : Sound("Entity Player Hurt Freeze", "entity.player.hurt_freeze")
    data object EntityPlayerHurtOnFire : Sound("Entity Player Hurt On Fire", "entity.player.hurt_on_fire")
    data object EntityPlayerLevelup : Sound("Entity Player Levelup", "entity.player.levelup")
    data object EntityPlayerSmallFall : Sound("Entity Player Small Fall", "entity.player.small_fall")
    data object EntityPlayerSplash : Sound("Entity Player Splash", "entity.player.splash")
    data object EntityPlayerSplashHighSpeed : Sound("Entity Player Splash High Speed", "entity.player.splash.high_speed")
    data object EntityPlayerSwim : Sound("Entity Player Swim", "entity.player.swim")
    data object EntityPlayerTeleport : Sound("Entity Player Teleport", "entity.player.teleport")
    data object EntityRabbitAmbient : Sound("Entity Rabbit Ambient", "entity.rabbit.ambient")
    data object EntityRabbitAttack : Sound("Entity Rabbit Attack", "entity.rabbit.attack")
    data object EntityRabbitDeath : Sound("Entity Rabbit Death", "entity.rabbit.death")
    data object EntityRabbitHurt : Sound("Entity Rabbit Hurt", "entity.rabbit.hurt")
    data object EntityRabbitJump : Sound("Entity Rabbit Jump", "entity.rabbit.jump")
    data object EntitySheepAmbient : Sound("Entity Sheep Ambient", "entity.sheep.ambient")
    data object EntitySheepDeath : Sound("Entity Sheep Death", "entity.sheep.death")
    data object EntitySheepHurt : Sound("Entity Sheep Hurt", "entity.sheep.hurt")
    data object EntitySheepShear : Sound("Entity Sheep Shear", "entity.sheep.shear")
    data object EntitySheepStep : Sound("Entity Sheep Step", "entity.sheep.step")
    data object EntitySilverfishAmbient : Sound("Entity Silverfish Ambient", "entity.silverfish.ambient")
    data object EntitySilverfishDeath : Sound("Entity Silverfish Death", "entity.silverfish.death")
    data object EntitySilverfishHurt : Sound("Entity Silverfish Hurt", "entity.silverfish.hurt")
    data object EntitySilverfishStep : Sound("Entity Silverfish Step", "entity.silverfish.step")
    data object EntitySkeletonAmbient : Sound("Entity Skeleton Ambient", "entity.skeleton.ambient")
    data object EntitySkeletonDeath : Sound("Entity Skeleton Death", "entity.skeleton.death")
    data object EntitySkeletonHorseAmbient : Sound("Entity Skeleton Horse Ambient", "entity.skeleton_horse_ambient")
    data object EntitySkeletonHorseAmbientWater : Sound("Entity Skeleton Horse Ambient Water", "entity.skeleton_horse_ambient_water")
    data object EntitySkeletonHorseDeath : Sound("Entity Skeleton Horse Death", "entity.skeleton_horse_death")
    data object EntitySkeletonHorseGallopWater : Sound("Entity Skeleton Horse Gallop Water", "entity.skeleton_horse.gallop_water")
    data object EntitySkeletonHorseHurt : Sound("Entity Skeleton Horse Hurt", "entity.skeleton_horse_hurt")
    data object EntitySkeletonHorseJumpWater : Sound("Entity Skeleton Horse Jump Water", "entity.skeleton_horse.jump_water")
    data object EntitySkeletonHorseStepWater : Sound("Entity Skeleton Horse Step Water", "entity.skeleton_horse.step_water")
    data object EntitySkeletonHorseSwim : Sound("Entity Skeleton Horse Swim", "entity.skeleton_horse.swim")
    data object EntitySkeletonHurt : Sound("Entity Skeleton Hurt", "entity.skeleton.hurt")
    data object EntitySkeletonShoot : Sound("Entity Skeleton Shoot", "entity.skeleton.shoot")
    data object EntitySkeletonStep : Sound("Entity Skeleton Step", "entity.skeleton.step")
    data object EntitySlimeAttack : Sound("Entity Slime Attack", "entity.slime.attack")
    data object EntitySlimeDeath : Sound("Entity Slime Death", "entity.slime.death")
    data object EntitySlimeDeathSmall : Sound("Entity Slime Death Small", "entity.slime.death_small")
    data object EntitySlimeHurt : Sound("Entity Slime Hurt", "entity.slime.hurt")
    data object EntitySlimeHurtSmall : Sound("Entity Slime Hurt Small", "entity.slime.hurt_small")
    data object EntitySlimeJump : Sound("Entity Slime Jump", "entity.slime.jump")
    data object EntitySlimeJumpSmall : Sound("Entity Slime Jump Small", "entity.slime.jump_small")
    data object EntitySlimeSquish : Sound("Entity Slime Squish", "entity.slime.squish")
    data object EntitySlimeSquishSmall : Sound("Entity Slime Squish Small", "entity.slime.squish_small")
    data object EntitySnowGolemAmbient : Sound("Entity Snow Golem Ambient", "entity.snow_golem.ambient")
    data object EntitySnowGolemDeath : Sound("Entity Snow Golem Death", "entity.snow_golem.death")
    data object EntitySnowGolemHurt : Sound("Entity Snow Golem Hurt", "entity.snow_golem.hurt")
    data object EntitySnowGolemShear : Sound("Entity Snow Golem Shear", "entity.snow_golem.shear")
    data object EntitySnowGolemShoot : Sound("Entity Snow Golem Shoot", "entity.snow_golem.shoot")
    data object EntitySnowballThrow : Sound("Entity Snowball Throw", "entity.snowball.throw")
    data object EntitySpiderAmbient : Sound("Entity Spider Ambient", "entity.spider.ambient")
    data object EntitySpiderDeath : Sound("Entity Spider Death", "entity.spider.death")
    data object EntitySpiderHurt : Sound("Entity Spider Hurt", "entity.spider.hurt")
    data object EntitySpiderStep : Sound("Entity Spider Step", "entity.spider.step")
    data object EntitySplashPotionBreak : Sound("Entity Splash Potion Break", "entity.splash_potion.break")
    data object EntitySplashPotionThrow : Sound("Entity Splash Potion Throw", "entity.splash_potion.throw")
    data object EntitySquidAmbient : Sound("Entity Squid Ambient", "entity.squid.ambient")
    data object EntitySquidDeath : Sound("Entity Squid Death", "entity.squid.death")
    data object EntitySquidHurt : Sound("Entity Squid Hurt", "entity.squid.hurt")
    data object EntitySquidSquirt : Sound("Entity Squid Squirt", "entity.squid.squirt")
    data object EntityTntPrimed : Sound("Entity Tnt Primed", "entity.tnt.primed")
    data object EntityVillagerAmbient : Sound("Entity Villager Ambient", "entity.villager.ambient")
    data object EntityVillagerDeath : Sound("Entity Villager Death", "entity.villager.death")
    data object EntityVillagerHurt : Sound("Entity Villager Hurt", "entity.villager.hurt")
    data object EntityVillagerNo : Sound("Entity Villager No", "entity.villager.no")
    data object EntityVillagerTrade : Sound("Entity Villager Trade", "entity.villager.trade")
    data object EntityVillagerYes : Sound("Entity Villager Yes", "entity.villager.yes")
    data object EntityWitchAmbient : Sound("Entity Witch Ambient", "entity.witch.ambient")
    data object EntityWitchCelebrate : Sound("Entity Witch Celebrate", "entity.witch.celebrate")
    data object EntityWitchDeath : Sound("Entity Witch Death", "entity.witch.death")
    data object EntityWitchDrink : Sound("Entity Witch Drink", "entity.witch.drink")
    data object EntityWitchHurt : Sound("Entity Witch Hurt", "entity.witch.hurt")
    data object EntityWitchThrow : Sound("Entity Witch Throw", "entity.witch.throw")
    data object EntityWitherAmbient : Sound("Entity Wither Ambient", "entity.wither.ambient")
    data object EntityWitherBreakBlock : Sound("Entity Wither Break Block", "entity.wither.break_block")
    data object EntityWitherDeath : Sound("Entity Wither Death", "entity.wither.death")
    data object EntityWitherHurt : Sound("Entity Wither Hurt", "entity.wither.hurt")
    data object EntityWitherShoot : Sound("Entity Wither Shoot", "entity.wither.shoot")
    data object EntityWitherSpawn : Sound("Entity Wither Spawn", "entity.wither.spawn")
    data object EntityWolfAmbient : Sound("Entity Wolf Ambient", "entity.wolf.ambient")
    data object EntityWolfDeath : Sound("Entity Wolf Death", "entity.wolf.death")
    data object EntityWolfGrowl : Sound("Entity Wolf Growl", "entity.wolf.growl")
    data object EntityWolfHowl : Sound("Entity Wolf Howl", "entity.wolf.howl")
    data object EntityWolfHurt : Sound("Entity Wolf Hurt", "entity.wolf.hurt")
    data object EntityWolfPant : Sound("Entity Wolf Pant", "entity.wolf.pant")
    data object EntityWolfShake : Sound("Entity Wolf Shake", "entity.wolf.shake")
    data object EntityWolfStep : Sound("Entity Wolf Step", "entity.wolf.step")
    data object EntityWolfWhine : Sound("Entity Wolf Whine", "entity.wolf.whine")
    data object EntityZombieAmbient : Sound("Entity Zombie Ambient", "entity.zombie.ambient")
    data object EntityZombieAttackIronDoor : Sound("Entity Zombie Attack Iron Door", "entity.zombie.attack.iron_door")
    data object EntityZombieAttackWoodenDoor : Sound("Entity Zombie Attack Wooden Door", "entity.zombie.attack.wooden_door")
    data object EntityZombieBreakWoodenDoor : Sound("Entity Zombie Break Wooden Door", "entity.zombie.break.wooden_door")
    data object EntityZombieConvertedToDrowned : Sound("Entity Zombie Converted To Drowned", "entity.zombie.converted_to_drowned")
    data object EntityZombieDeath : Sound("Entity Zombie Death", "entity.zombie.death")
    data object EntityZombieDestroyEgg : Sound("Entity Zombie Destroy Egg", "entity.zombie.destroy_egg")
    data object EntityZombieHorseAmbient : Sound("Entity Zombie Horse Ambient", "entity.zombie.horse_ambient")
    data object EntityZombieHorseDeath : Sound("Entity Zombie Horse Death", "entity.zombie.horse_death")
    data object EntityZombieHorseHurt : Sound("Entity Zombie Horse Hurt", "entity.zombie.horse_hurt")
    data object EntityZombieHurt : Sound("Entity Zombie Hurt", "entity.zombie.hurt")
    data object EntityZombieInfect : Sound("Entity Zombie Infect", "entity.zombie.infect")
    data object EntityZombieStep : Sound("Entity Zombie Step", "entity.zombie.step")
    data object EntityZombieVillagerAmbient : Sound("Entity Zombie Villager Ambient", "entity.zombie_villager.ambient")
    data object EntityZombieVillagerConverted : Sound("Entity Zombie Villager Converted", "entity.zombie_villager.converted")
    data object EntityZombieVillagerCure : Sound("Entity Zombie Villager Cure", "entity.zombie_villager.cure")
    data object EntityZombieVillagerDeath : Sound("Entity Zombie Villager Death", "entity.zombie_villager.death")
    data object EntityZombieVillagerHurt : Sound("Entity Zombie Villager Hurt", "entity.zombie_villager.hurt")
    data object EntityZombieVillagerStep : Sound("Entity Zombie Villager Step", "entity.zombie_villager.step")
    data object EntityZombifiedPiglinAmbient : Sound("Entity Zombified Piglin Ambient", "entity.zombified_piglin.ambient")
    data object EntityZombifiedPiglinAngry : Sound("Entity Zombified Piglin Angry", "entity.zombified_piglin.angry")
    data object EntityZombifiedPiglinDeath : Sound("Entity Zombified Piglin Death", "entity.zombified_piglin.death")
    data object EntityZombifiedPiglinHurt : Sound("Entity Zombified Piglin Hurt", "entity.zombified_piglin.hurt")
    data object ItemCropPlant : Sound("Item Crop Plant", "item.crop.plant")
    data object ItemDyeUse : Sound("Item Dye Use", "item.dye.use")
    data object ItemFirechargeUse : Sound("Item Firecharge Use", "item.firecharge.use")
    data object ItemFlintandsteelUse : Sound("Item Flintandsteel Use", "item.flintandsteel.use")
    data object ItemHoeTill : Sound("Item Hoe Till", "item.hoe.till")
    data object ItemInkSacUse : Sound("Item Ink Sac Use", "item.ink_sac.use")
    data object ItemNetherWartPlant : Sound("Item Nether Wart Plant", "item.nether_wart.plant")
    data object MusicCreative : Sound("Music Creative", "music.creative")
    data object MusicCredits : Sound("Music Credits", "music.credits")
    data object MusicDisc11 : Sound("Music Disc 11", "music.disc.11")
    data object MusicDisc13 : Sound("Music Disc 13", "music.disc.13")
    data object MusicDisc5 : Sound("Music Disc 5", "music.disc.5")
    data object MusicDiscBlocks : Sound("Music Disc Blocks", "music.disc.blocks")
    data object MusicDiscCat : Sound("Music Disc Cat", "music.disc.cat")
    data object MusicDiscChirp : Sound("Music Disc Chirp", "music.disc.chirp")
    data object MusicDiscFar : Sound("Music Disc Far", "music.disc.far")
    data object MusicDiscMall : Sound("Music Disc Mall", "music.disc.mall")
    data object MusicDiscMellohi : Sound("Music Disc Mellohi", "music.disc.mellohi")
    data object MusicDiscStal : Sound("Music Disc Stal", "music.disc.stal")
    data object MusicDiscStrad : Sound("Music Disc Strad", "music.disc.strad")
    data object MusicDiscWait : Sound("Music Disc Wait", "music.disc.wait")
    data object MusicDiscWard : Sound("Music Disc Ward", "music.disc.ward")
    data object MusicDragon : Sound("Music Dragon", "music.dragon")
    data object MusicEnd : Sound("Music End", "music.end")
    data object MusicGame : Sound("Music Game", "music.game")
    data object MusicMenu : Sound("Music Menu", "music.menu")
    data object MusicOverworldBadlands : Sound("Music Overworld Badlands", "music.overworld.badlands")
    data object MusicOverworldBambooJungle : Sound("Music Overworld Bamboo Jungle", "music.overworld.bamboo_jungle")
    data object MusicOverworldDesert : Sound("Music Overworld Desert", "music.overworld.desert")
    data object MusicOverworldFlowerForest : Sound("Music Overworld Flower Forest", "music.overworld.flower_forest")
    data object MusicOverworldForest : Sound("Music Overworld Forest", "music.overworld.forest")
    data object MusicOverworldFrozenPeaks : Sound("Music Overworld Frozen Peaks", "music.overworld.frozen_peaks")
    data object MusicOverworldGrove : Sound("Music Overworld Grove", "music.overworld.grove")
    data object MusicOverworldJaggedPeaks : Sound("Music Overworld Jagged Peaks", "music.overworld.jagged_peaks")
    data object MusicOverworldJungle : Sound("Music Overworld Jungle", "music.overworld.jungle")
    data object MusicOverworldMeadow : Sound("Music Overworld Meadow", "music.overworld.meadow")
    data object MusicOverworldOldGrowthTaiga : Sound("Music Overworld Old Growth Taiga", "music.overworld.old_growth_taiga")
    data object MusicOverworldSnowySlopes : Sound("Music Overworld Snowy Slopes", "music.overworld.snowy_slopes")
    data object MusicOverworldSparseJungle : Sound("Music Overworld Sparse Jungle", "music.overworld.sparse_jungle")
    data object MusicOverworldStonyPeaks : Sound("Music Overworld Stony Peaks", "music.overworld.stony_peaks")
    data object MusicOverworldSwamp : Sound("Music Overworld Swamp", "music.overworld.swamp")
    data object OtherRain : Sound("Other Rain", "other.rain")
    data object OtherRainAbove : Sound("Other Rain Above", "other.rain.above")
    data object Othergeneral : Sound("Other general", "other.general")
    data object UiButtonClick : Sound("Ui Button Click", "ui.button.click")

    data object NeutralHurtFallBig : Sound("Neutral Hurt Fall Big", "game.neutral.hurt.fall.big")
    data object NeutralHurtFallSmall : Sound("Neutral Hurt Fall Small", "game.neutral.hurt.fall.small")
    data object HostileHurtFallBig : Sound("Hostile Hurt Fall Big", "game.hostile.hurt.fall.big")
    data object HostileHurtFallSmall : Sound("Hostile Hurt Fall Small", "game.hostile.hurt.fall.small")
    data object NeutralHurt : Sound("Neutral Hurt", "game.neutral.hurt")
    data object HostileHurt : Sound("Hostile Hurt", "game.hostile.hurt")
    data object PlayerDie : Sound("Player Die", "game.player.die")
    data object NeutralDie : Sound("Neutral Die", "game.neutral.die")
    data object HostileDie : Sound("Hostile Die", "game.hostile.die")
    data object DigCloth : Sound("Dig Cloth", "dig.cloth")
    data object DigGravel : Sound("Dig Gravel", "dig.gravel")
    data object DigSand : Sound("Dig Sand", "dig.sand")
    data object DigSnow : Sound("Dig Snow", "dig.snow")
    data object DigStone : Sound("Dig Stone", "dig.stone")
    data object DigWood : Sound("Dig Wood", "dig.wood")
    data object FireFire : Sound("Fire Fire", "fire.fire")
    data object FireIgnite : Sound("Fire Ignite", "fire.ignite")
    data object LiquidLava : Sound("Liquid Lava", "liquid.lava")
    data object NeutralSwimSplash : Sound("Neutral Swim Splash", "game.neutral.swim.splash")
    data object HostileSwimSplash : Sound("Hostile Swim Splash", "game.hostile.swim.splash")
    data object NeutralSwim : Sound("Neutral Swim", "game.neutral.swim")
    data object HostileSwim : Sound("Hostile Swim", "game.hostile.swim")
    data object LiquidWater : Sound("Liquid Water", "liquid.water")
    data object MinecartBase : Sound("Minecart Base", "minecart.base")
    data object MinecartInside : Sound("Minecart Inside", "minecart.inside")
    data object CreeperPrimedLegacy : Sound("Creeper Primed Legacy", "creeper.primed")
    data object PotionSmash : Sound("Potion Smash", "game.potion.smash")
    data object RandomSplash : Sound("Random Splash", "random.splash")
    data object Records11 : Sound("Records 11", "records.11")
    data object Records13 : Sound("Records 13", "records.13")
    data object RecordsBlocks : Sound("Records Blocks", "records.blocks")
    data object RecordsCat : Sound("Records Cat", "records.cat")
    data object RecordsChirp : Sound("Records Chirp", "records.chirp")
    data object RecordsFar : Sound("Records Far", "records.far")
    data object RecordsMall : Sound("Records Mall", "records.mall")
    data object RecordsMellohi : Sound("Records Mellohi", "records.mellohi")
    data object RecordsStal : Sound("Records Stal", "records.stal")
    data object RecordsStrad : Sound("Records Strad", "records.strad")
    data object RecordsWait : Sound("Records Wait", "records.wait")
    data object RecordsWard : Sound("Records Ward", "records.ward")
    data object StepCloth : Sound("Step Cloth", "step.cloth")
    data object StepGrass : Sound("Step Grass", "step.grass")
    data object StepGravel : Sound("Step Gravel", "step.gravel")
    data object StepLadder : Sound("Step Ladder", "step.ladder")
    data object StepSand : Sound("Step Sand", "step.sand")
    data object StepSnow : Sound("Step Snow", "step.snow")
    data object StepStone : Sound("Step Stone", "step.stone")
    data object StepWood : Sound("Step Wood", "step.wood")
    data object PistonIn : Sound("Piston In", "tile.piston.in")
    data object PistonOut : Sound("Piston Out", "tile.piston.out")
    data object MusicGameCreative : Sound("Music Game Creative", "music.game.creative")
    data object MusicGameEnd : Sound("Music Game End", "music.game.end")
    data object MusicGameEndDragon : Sound("Music Game End Dragon", "music.game.end.dragon")
    data object MusicGameEndCredits : Sound("Music Game End Credits", "music.game.end.credits")
    data object MusicGameNether : Sound("Music Game Nether", "music.game.nether")

    companion object {
        val entries: List<Sound> = Sound::class.sealedSubclasses.mapNotNull { it.objectInstance }

        fun fromKey(key: String): Sound {
            for (entry in entries) {
                if (entry.key.equals(key, ignoreCase = true)) {
                    return entry
                }
                if (entry.label.equals(key, ignoreCase = true)) {
                    return entry
                }
            }
            return Custom(key)
        }
    }
}